[theme]
base = "dark"
primaryColor = "#00FFAA"
backgroundColor = "#0B0F17"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s — %(levelname)s — %(message)s"
