# Streamlit secrets template for BlockVista Terminal
KITE_API_KEY = "<your_kite_api_key>"
KITE_API_SECRET = "<your_kite_api_secret>"
KITE_API_ACCESS_TOKEN = "<your_access_token>"
OPENAI_API_KEY = "<your_openai_api_key>"
NEWS_API_KEY = "<your_news_api_key>"
DB_URL = "<your_database_connection_url>"
# Add more keys as needed for other integrations
